#! /bin/sh

###---Autostart---###
# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# Start polybar
$HOME/.config/bspwm/launch.sh &
# Start bspswallow
pgrep bspswallow || bspswallow &
# Change capslock
$HOME/.config/bspwm/caps.sh &
# Set keyboard layout to fr and ara
setxkbmap -option grp:alt_shift_toggle fr,ara &
# Start other programes
nm-applet &
nitrogen --restore &
picom  &
lxsession &

bspc monitor -d 1 2 3 4 5 6 7 8 9


###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#434C5E"
bspc config active_border_color	"#88C0D0"
bspc config focused_border_color "#EBCB8B"
bspc config presel_feedback_color"#81A1C1"
bspc config urgent_border_color "#BF616A"

###---Monitor And Desktop Settings----###
bspc config top_padding 25
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
bspc rule -a mpv state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above
